spring.application.name=homeworksubmission

spring.datasource.url=jdbc:mysql://localhost:3306/homework_portal
spring.datasource.username=root
spring.datasource.password=Sankoju@123122

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT configuration
app.jwt.secret=mysupersecurejwtsecretkeyforhomeworkportal2026
app.jwt.expiration-ms=86400000

file.upload-dir=uploads/assignments