spring.application.name=homeworksubmission
server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://dpg-d6qit97gi27c73a477g0-a.oregon-postgres.render.com:5432/homework_portal
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=abhi
spring.datasource.password=oUut2gSVl5HPffhNaBGzFRiNUbMjJ5lx

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# JWT configuration
app.jwt.secret=mysupersecurejwtsecretkeyforhomeworkportal2026
app.jwt.expiration-ms=86400000

file.upload-dir=uploads/assignments

#postgresql://abhi:oUut2gSVl5HPffhNaBGzFRiNUbMjJ5lx@dpg-d6qit97gi27c73a477g0-a.oregon-postgres.render.com/homework_portal